language: go
sudo: required

go:
 - 1.9.x

dist: trusty

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install && cd -
  - glide install

script:
  - ./build.sh
