language: go
sudo: required
go_import_path: github.com/lucaslorentz/caddy-supervisor

go:
 - 1.11.x

dist: trusty

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - ./build.sh
